twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    globals:
        titre: 'le titre que je veux réutiliser'

when@test:
    twig:
        strict_variables: true
